services:
  rockpaperscissors.api:
    image: rockpaperscissors.api
    build:
      context: .
      dockerfile: RockPaperScissors.API/Dockerfile
    ports:
      - "8000:8080"
    environment:
      PostgresOptions__DefaultConnection : Server=postgres;Port=5432;Database=postgres;User Id=postgres;Password=postgres;
      MongoOptions__ConnectionString: mongodb://mongo-db:27017
      MongoOptions__DatabaseName: RatingDb
      MongoOptions__CollectionName: Rating
      JwtOptions__Issuer: http://example.com
      JwtOptions__Audience: http://example.com
      JwtOptions__Key: 943573894759348593845793
    depends_on:
      - postgres
      - mongo-db
      
  postgres:
    image: postgres:alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5450:5432'
  
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27018:27017"
            